version: '3'
services:
  editor: # service name
    build:
      context: . # 当前目录
      dockerfile: Dockerfile # 基于 Dockerfile 构建
    image: editor # 依赖于当前 Dockerfile 创建出来的镜像
    container_name: editor
    ports:
      - 5000:80 # 宿主机通过 5000 访问