name: 自动部署新版本到服务器
# push 到 master 后被触发
on:
  push:
    branches:
      - master
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      # checkout 代码
      - uses: actions/checkout@v2
      # 创建 env 文件
      # build docker image
      # start the app
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PWD }}
      # 使用正确的github tag 对应ACR tag 进行 docker build
      - name: Build image for ACR docker
        run: docker build --tag "registry.cn-hangzhou.aliyuncs.com/redell/editor:${{github.sha}}" .
      # 使用标记的 tag 进行 push
      - name: Push Image to ACR
        run: docker push registry.cn-hangzhou.aliyuncs.com/redell/editor:${{github.sha}}
      # 查找 docker-compose.yml 文件 并且完成版本替换
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{tag}}"
          replace: ${{github.sha}}
          include: "docker-compose.yml"
      - run: cat docker-compose.yml
      # 拷贝必须文件到一个文件夹，包括 editor.conf, docker-compose.yml, dist
      - name: 'copy necessary files in to one folder'
        run: |
          mkdir editor
          cp editor.conf docker-compose.yml editor
          ls -a editor
      # 通过 scp 拷贝必须文件到服务器
      - name: 'copy editor folder via scp'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          source: 'editor'
          target: '~'
      # 通过 SSH 登录然后重启服务
      - name: executing ssh and restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          # * 登录阿里云 ACR
          # 停止服务 docker-compose down
          # 启动服务 docker-compose up
          # 清理工作
          script: |
            docker login --username=${{ secrets.ACR_USERNAME }} --password=${{ secrets.ACR_PWD }} registry.cn-hangzhou.aliyuncs.com
            cd ~/editor/
            docker-compose down
            docker-compose up -d
            docker cp editor:/app/dist/ /data/www/editor
            cp editor.conf /etc/nginx/conf.d/
            nginx -s reload
            docker logout registry.cn-hangzhou.aliyuncs.com
