# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.GJS_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "1.116.156.44" >> ~/.ssh/known_hosts
      - name: deploy # 部署
        run: |
          ssh root@1.116.156.44 "
            cd /lego/editor-react;
            git checkout master;
            git branch -D dev;
            git checkout -b dev origin/dev;
            git pull origin dev;
            docker-compose build editor;
            docker-compose up -d;
          "
      - name: delete ssh key # 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
